name: Aprendiendo GitHub Actions
run-name: Estoy aprendiendo GitHub Actions
on: [push]

jobs:
  hola-mundo:
    runs-on: ubuntu-latest  # Asegúrate de que esté correctamente indentado

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: aprendiendo-github-actions

      - name: Instalar JDK
        run: sudo apt-get install openjdk-11-jdk -y

      - name: Compilar Java
        run: javac Main.java

      - name: Correr script
        run: java Main
